hkActions := []
hkActions["GAME"] := []
hkActions["COMBOS"] := []
hkActions["POUCH"] := []
hkActions["BELT"] := []
hkActions["SPELL"] := []
hkActions["GESTURES"] := []
hkActions["CONFIG"] := []
hkActions["GAME"]["MOVE_CONTROL"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["MOVE_FORWARD"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["MOVE_BACKWARDS"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["MOVE_LEFT"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["MOVE_RIGHT"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["DODGE"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["JUMP"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["CROUCH"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["CAMUP"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"0"}
hkActions["GAME"]["CAMDOWN"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"0"}
hkActions["GAME"]["CAMLEFT"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["CAMRIGHT"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["LOCKON"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["DUP"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["DDOWN"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["DRIGHT"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["DLEFT"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["ATTACK"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["SATTACK"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["GUARD"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["SKILL"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["USEITEM"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["GAME"]["EVENT_ACTION"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["POUCH"]["UPOUCH"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["POUCH"]["LPOUCH"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["POUCH"]["RPOUCH"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["POUCH"]["DPOUCH"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["POUCH"]["5POUCH"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["POUCH"]["6POUCH"]:= { "type": "reference","label": "", "animationtime": "0", "enabled":"1"}
hkActions["COMBOS"]["AUTORUN"]:= { "type": "func","label": "S_AutoRun", "animationtime": "0", "enabled":"1"}
hkActions["COMBOS"]["PARRY"]:= { "type": "func","label": "S_Parry", "animationtime": "350", "enabled":"1"}
hkActions["COMBOS"]["2H_LEFT"]:= { "type": "func","label": "S_2H_Left", "animationtime": "500", "enabled":"1"}
hkActions["COMBOS"]["2H_RIGHT"]:= { "type": "func","label": "S_2H_Right", "animationtime": "500", "enabled":"1"}
hkActions["COMBOS"]["LEFTARMEMENT"]:= { "type": "func","label": "S_LeftArmement", "animationtime": "500", "enabled":"1"}
hkActions["COMBOS"]["RIGHTARMEMENT"]:= { "type": "func","label": "S_RightArmement", "animationtime": "500", "enabled":"1"}
hkActions["COMBOS"]["JUMPDUALWEILD"]:= { "type": "func","label": "S_JumpDualWeild", "animationtime": "500", "enabled":"1"}
hkActions["COMBOS"]["CROUCH"]:= { "type": "func","label": "S_Crouch", "animationtime": "500", "enabled":"1"}
hkActions["COMBOS"]["JUMP"]:= { "type": "func","label": "S_Jump", "animationtime": "500", "enabled":"1"}
hkActions["COMBOS"]["JUMPSTRONG"]:= { "type": "func","label": "S_JumpStrong", "animationtime": "500", "enabled":"1"}
hkActions["COMBOS"]["TOGGLESPELLHAND"]:= { "type": "func","label": "S_ToggleSpellHand", "animationtime": "500", "enabled":"1"}
hkActions["COMBOS"]["TOGGLEDEBUG"]:= { "type": "func","label": "S_ToggleDebug", "animationtime": "0", "enabled":"1"}
hkActions["BELT"]["USEBELTSLOT1"]:= { "type": "func","label": "S_UseBelt1", "animationtime": "500", "enabled":"1"}
hkActions["BELT"]["USEBELTSLOT2"]:= { "type": "func","label": "S_UseBelt2", "animationtime": "500", "enabled":"1"}
hkActions["BELT"]["USEBELTSLOT3"]:= { "type": "func","label": "S_UseBelt3", "animationtime": "500", "enabled":"1"}
hkActions["BELT"]["USEBELTSLOT4"]:= { "type": "func","label": "S_UseBelt4", "animationtime": "500", "enabled":"1"}
hkActions["BELT"]["USEBELTSLOT5"]:= { "type": "func","label": "S_UseBelt5", "animationtime": "500", "enabled":"1"}
hkActions["BELT"]["USEBELTSLOT6"]:= { "type": "func","label": "S_UseBelt6", "animationtime": "500", "enabled":"1"}
hkActions["BELT"]["USEBELTSLOT7"]:= { "type": "func","label": "S_UseBelt7", "animationtime": "500", "enabled":"1"}
hkActions["BELT"]["USEBELTSLOT8"]:= { "type": "func","label": "S_UseBelt8", "animationtime": "500", "enabled":"1"}
hkActions["BELT"]["USEBELTSLOT9"]:= { "type": "func","label": "S_UseBelt9", "animationtime": "500", "enabled":"1"}
hkActions["BELT"]["USEBELTSLOT10"]:= { "type": "func","label": "S_UseBelt10", "animationtime": "500", "enabled":"1"}
hkActions["BELT"]["SWITCHBELTSLOT1"]:= { "type": "func","label": "S_Belt_reset", "animationtime": "200", "enabled":"1"}
hkActions["BELT"]["SWITCHBELTSLOT2"]:= { "type": "func","label": "S_SwitchBelt2", "animationtime": "200", "enabled":"1"}
hkActions["BELT"]["SWITCHBELTSLOT3"]:= { "type": "func","label": "S_SwitchBelt3", "animationtime": "200", "enabled":"1"}
hkActions["BELT"]["SWITCHBELTSLOT4"]:= { "type": "func","label": "S_SwitchBelt4", "animationtime": "200", "enabled":"1"}
hkActions["BELT"]["SWITCHBELTSLOT5"]:= { "type": "func","label": "S_SwitchBelt5", "animationtime": "200", "enabled":"1"}
hkActions["BELT"]["SWITCHBELTSLOT6"]:= { "type": "func","label": "S_SwitchBelt6", "animationtime": "200", "enabled":"1"}
hkActions["BELT"]["SWITCHBELTSLOT7"]:= { "type": "func","label": "S_SwitchBelt7", "animationtime": "200", "enabled":"1"}
hkActions["BELT"]["SWITCHBELTSLOT8"]:= { "type": "func","label": "S_SwitchBelt8", "animationtime": "200", "enabled":"1"}
hkActions["BELT"]["SWITCHBELTSLOT9"]:= { "type": "func","label": "S_SwitchBelt9", "animationtime": "200", "enabled":"1"}
hkActions["BELT"]["SWITCHBELTSLOT10"]:= { "type": "func","label": "S_SwitchBelt10", "animationtime": "200", "enabled":"1"}
hkActions["GESTURES"]["GESTURE1"]:= { "type": "func","label": "S_gesture_1", "animationtime": "1000", "enabled":"1"}
hkActions["GESTURES"]["GESTURE2"]:= { "type": "func","label": "S_gesture_2", "animationtime": "1000", "enabled":"1"}
hkActions["GESTURES"]["GESTURE3"]:= { "type": "func","label": "S_gesture_3", "animationtime": "1000", "enabled":"1"}
hkActions["GESTURES"]["GESTURE4"]:= { "type": "func","label": "S_gesture_4", "animationtime": "1000", "enabled":"1"}
hkActions["GESTURES"]["GESTURE5"]:= { "type": "func","label": "S_gesture_5", "animationtime": "1000", "enabled":"1"}
hkActions["GESTURES"]["GESTURE6"]:= { "type": "func","label": "S_gesture_6", "animationtime": "1000", "enabled":"1"}
hkActions["SPELL"]["USESPELLSLOT1"]:= { "type": "func","label": "S_Spell1", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["USES_SpellSlot2"]:= { "type": "func","label": "S_Spell2", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["USES_SpellSlot3"]:= { "type": "func","label": "S_Spell3", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["USES_SpellSlot4"]:= { "type": "func","label": "S_Spell4", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["USES_SpellSlot5"]:= { "type": "func","label": "S_Spell5", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["USES_SpellSlot6"]:= { "type": "func","label": "S_Spell6", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["USES_SpellSlot7"]:= { "type": "func","label": "S_Spell7", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["USES_SpellSlot8"]:= { "type": "func","label": "S_Spell8", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["USES_SpellSlot9"]:= { "type": "func","label": "S_Spell9", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["USES_SpellSlot10"]:= { "type": "func","label": "S_Spell10", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["SWITCHSPELLSLOT1"]:= { "type": "func","label": "S_SpellReset", "animationtime": "500", "enabled":"1"}
hkActions["SPELL"]["SWITCHS_SpellSlot2"]:= { "type": "func","label": "S_SpellSlot2", "animationtime": "200", "enabled":"1"}
hkActions["SPELL"]["SWITCHS_SpellSlot3"]:= { "type": "func","label": "S_SpellSlot3", "animationtime": "200", "enabled":"1"}
hkActions["SPELL"]["SWITCHS_SpellSlot4"]:= { "type": "func","label": "S_SpellSlot4", "animationtime": "200", "enabled":"1"}
hkActions["SPELL"]["SWITCHS_SpellSlot5"]:= { "type": "func","label": "S_SpellSlot5", "animationtime": "200", "enabled":"1"}
hkActions["SPELL"]["SWITCHS_SpellSlot6"]:= { "type": "func","label": "S_SpellSlot6", "animationtime": "200", "enabled":"1"}
hkActions["SPELL"]["SWITCHS_SpellSlot7"]:= { "type": "func","label": "S_SpellSlot7", "animationtime": "200", "enabled":"1"}
hkActions["SPELL"]["SWITCHS_SpellSlot8"]:= { "type": "func","label": "S_SpellSlot8", "animationtime": "200", "enabled":"1"}
hkActions["SPELL"]["SWITCHS_SpellSlot9"]:= { "type": "func","label": "S_SpellSlot9", "animationtime": "200", "enabled":"1"}
hkActions["SPELL"]["SWITCHS_SpellSlot10"]:= { "type": "func", "label": "S_SpellSlot10", "animationtime": "200", "enabled":"1"}
